version: '3.7'

services:
  stripe-webhooks:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    container_name: stripe-webhooks
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm run start